#------------------
#All Available Enchantments
#Protection
#Fire Protection
#Feather Falling
#Blast Protection
#Projectile Protection
#Respiration
#Aqua Infinity
#Thorns
#Depth Strider
#Frost Walker
#Curse of Binding
#Sharpness
#Smite
#Bane of Arthropods
#Knockback
#Fire Aspect
#Looting
#Sweeping Edge
#Efficiency
#Silk Touch
#Unbreaking
#Fortune
#Power
#Punch
#Flame
#Lure
#Loyalty
#Impaling
#Riptide
#Channeling
#Mending
#Curse of Vanishing
#------------------
#Available Boss Types
#Skeleton
#Zombie
#Slime
#Witch
#Iron Golem
#Spider
#EnderMan
#Blaze
#Silver Fish
#Wither
#Wither Boss
#Ender Dragon
#Magma Cube
#Illusioner
#Vindicator
#Silverfish
#Drowned
#Shulker
#Stray
#Evoker
#Endermite
#Vex
#Phantom
#Guardian
#Elder Guardian
#Husk
#------------------
 

Messages:
  NoPerms: "You do not have permissions to use this command!"
  PlayersOnly: "This command can only be used by players!"
  
Settings:
  InventoryName: "&4&l&nThe Great Bosses"
  #Must be a factor of 9
  InventorySlots: 9
   #Kills all bosses when plugin is disabled (Server restart or reboot)
  KillAll: true
  
Testing: false
  
Bosses: 
  Skeletor:
    GUI:
      #Item used to spawn the Boss
      Item: 'Stone' 
      #The Slot in the GUI
      Slot: 5 
      #The name of the Item
      Name: '&6&lSkeletor Boss' 
      #The lore on the item
      Lore: 
        - '&3The Great Skeletor Boss'
        - '&aCost: &6%Cost%'
      #How much the Spawn Egg Costs
      Cost: 20 
      #The message when it is Bought
      BuyingMessage: '&3Thank you for buying &6&l&nThe Skeletor Boss&3.' 
    SpawnEgg:
      Item: 'Stone'
      Name: '&6&lSkeletor Boss Egg'
      Lore:
        - '&7Right click a block to'
        - '&7Spawn the Boss'
    Boss:
      #Name of the Boss
      Name: '&6&l&nSkeletor Boss' 
      #The Bosses Health
      Health: 10 
      #Type of Boss
      BossType: 'Skeleton' 
      #Armor Type
      Armor:
         Helment: 
            Type: 'Gold'
            Enchants:
               - 'Protection:5'
         Chestplate: 
            Type: 'Diamond'
            Enchants:
               - 'Protection:5'
         Leggings: 
            Type: 'Chain'
            Enchants: 
               - 'Protection:5'
         Boots: 
            Type: 'None'
            Enchants:
               - 'None'
      #Item that is in the bosses main hand.
      MainHand:
         Type: "Stick"
         Enchants:
            - 'Knockback:10'
            - 'Luck of the Sea:5'
      #Item in the bosses off hand
      OffHand:
         Type: "Shield"
         Enchantments:
            - 'Unbreaking:10'
            - 'Mending:5'
      #Drops normal thing the Mob would drop on death
      NatualDrops: false 
      #Drops custom items 
      #Format: Type (What the item is) Name (Name of the item) Lore (The lore of the item commas seperate the lines) Enchant:Power
      CustomDrops: 
        AwesomeStone:
           Type: 'Stone'
           Name: '&6Stone'
           Lore: 
              - '&7This is a cool'
              - '&4Piece of Stone' 
           Enchants:
              - 'Knockback:3'
        WhackStick:
           Type: 'Blaze_Rod'
           Name: '&6Whack-A-Mole'
           Lore:
              - '&7LELEL'
           Enchants:
              - 'Sharpness:255'
              - 'Luck of the Sea:255'
      MessageToKiller:
        - '&c&lYou have just killed the Boss.'
      Commands:
        - 'eco give %Player% 1000'